
module.exports = {
    "FORM_VIEW_COUNTRIES_FETCH": "FORM_VIEW_COUNTRIES_FETCH",
    "FORM_VIEW_COUNTRIES_SUCCESS": "FORM_VIEW_COUNTRIES_SUCCESS",
    "FORM_VIEW_COUNTRIES_ERROR": "FORM_VIEW_COUNTRIES_ERROR",
    "FORM_VIEW_SAVE": "FORM_VIEW_SAVE",
    "FORM_VIEW_SET_TEXT": "FORM_VIEW_SET_TEXT"
};